name: azure.governance.ci$(Rev:.r)

trigger:
  batch: "true"
  branches:
    include:
    - master
  paths:
    include:
    - src/terraform

pr: none

variables:
- name: TF_INPUT
  value: "false"
- name: TF_IN_AUTOMATION
  value: "true"

stages:

- stage: dev

  variables:
    - group: azuregovernancedev
    - group: azuregovernancedevsecret
    - name: TF_VERSION
      value: 0.12.17
    - name: TF_CLI_ARGS_init
      value:

  jobs:

  - job: Terraform
    displayName: Terraform Init-Plan
    pool:
      vmImage: 'ubuntu-latest'

    container:
      image: rjfmachado.azurecr.io/terraform:${{ variables['TF_VERSION'] }}
      endpoint: rjfmachado.containers

    steps:
      - bash: |
          printenv | grep ARM
          printend | grep TF_
        displayName: "printenv"
        name: printenvARM
        workingDirectory: src/terraform
        enabled: "true"
        env:
          ARM_CLIENT_SECRET: $(tfClientSecret)

      - template: /pipelines/templates/tf-init-plan.yaml
        parameters:
          tfCliInit: "-backend=true -backend-config=dev.stage"