name: azure.governance.ci$(Rev:.r)

trigger:
  batch: "true"
  branches:
    include:
    - master
  paths:
    include:
    - src/terraform

pr: none

variables:
- name: TF_INPUT
  value: "false"
- name: TF_IN_AUTOMATION
  value: "true"

stages:

- stage: dev

  variables:
    - group: azuregovernancedev
    - name: TF_CLI_ARGS_init
      value: "-backend=true -backend-config=../setup/dev.env"

  jobs:

  - job: Terraform
    displayName: Terraform Init-Plan
    pool:
      vmImage: 'ubuntu-latest'

    container:
      image: rjfmachado.azurecr.io/terraform:${{ variables['terraformVersion'] }}
      endpoint: rjfmachado.containers

    steps:
      - bash: |
          printenv
        displayName: "printenv"
        name: printenvarm
        workingDirectory: src/terraform
        enabled: "true"