name: Daily Validation$(Rev:.r)

trigger: none

schedules:
- cron: 0 0 * * *
  displayName: Ops Validation Build (Midnight)
  branches:
    include:
    - master
  always: true

pr: none

variables:
- name: terraformVersion
  value: 0.12.20

stages:

- stage: dev

  variables:
    - name: deploymentStage
      value: "dev"
    - name: stateStorageAccountName
      value: "tfazuregovernancedev"
    - name: stateContainerName
      value: "dev"
    - name: stateKey
      value: "terraform.tfstate"
    - group: azuregovernancedev

  jobs:

  - job: Terraform
    displayName: Azure Governance Ops - Dev
    pool:
      vmImage: 'ubuntu-latest'

    container:
      image: rjfmachado.azurecr.io/terraform:${{ variables['terraformVersion'] }}
      endpoint: rjfmachado.containers

    steps:

    - template: /build/templates/terraform-stage-ops.yml
      parameters:
        client_secret: $(ARM_CLIENT_SECRET)
        client_id: $(ARM_CLIENT_ID)
        tenant_id: $(ARM_TENANT_ID)
        subscription_id: $(ARM_SUBSCRIPTION_ID)
        storage_account_name: $(stateStorageAccountName)
        container_name: $(stateContainerName)
        key: $(stateKey)
        deploymentStage: $(deploymentStage)

- stage: prod

  variables:
    - name: deploymentStage
      value: "prod"
    - name: stateStorageAccountName
      value: "tfazuregovernanceprod"
    - name: stateContainerName
      value: "prod"
    - name: stateKey
      value: "terraform.tfstate"
    - group: azuregovernanceprod

  jobs:

  - job: Terraform
    displayName: Azure Governance Ops - Production
    pool:
      vmImage: 'ubuntu-latest'

    container:
      image: rjfmachado.azurecr.io/terraform:${{ variables['terraformVersion'] }}
      endpoint: rjfmachado.containers

    steps:

    - template: /build/templates/terraform-stage-ops.yml
      parameters:
        client_secret: $(ARM_CLIENT_SECRET)
        client_id: $(ARM_CLIENT_ID)
        tenant_id: $(ARM_TENANT_ID)
        subscription_id: $(ARM_SUBSCRIPTION_ID)
        storage_account_name: $(stateStorageAccountName)
        container_name: $(stateContainerName)
        key: $(stateKey)
        deploymentStage: $(deploymentStage)
