name: azure.governance.envrelease$(Rev:.r)

trigger: none

pr: none

variables:
  - name: TF_INPUT
    value: "false"
  - name: TF_IN_AUTOMATION
    value: "true"
  - name: TF_VERSION
    value: 0.12.19

stages:
  - stage: publishArtifacts

    jobs:
      - job: publishTerraform
        displayName: Publish Azure Governance Terraform files/plans.

        pool:
          vmImage: "ubuntu-latest"

        steps:
          - publish: src/terraform
            displayName: "Release Azure Governance."
            artifact: releaseAzureGovernance
            enabled: "true"

      - job: terraformInstall
        displayName: Terraform (Install)

        pool:
          vmImage: "ubuntu-latest"

        steps:
          - template: /pipelines/templates/tf-install.yaml
            parameters:
              tfVersion: $(TF_VERSION)

      - job: publishDevPlan
        displayName: Publish dev plan
        variables:
          - group: azuregovernancedev
          - group: azuregovernancedevsecret
        pool:
          vmImage: "ubuntu-latest"
        dependsOn: terraformInstall
        steps:
          - template: /pipelines/templates/tf-init-plan.yaml
            parameters:
              tfCliInit: -backend=true -backend-config=dev.stage
              tfCliPlan: -out dev.plan -var-file=dev.tfvars.json

          - publish: src/terraform/dev.plan
            displayName: "Publish Dev Plan"
            artifact: releaseAzureGovernancedevplan
            enabled: "true"

      - job: publishProdPlan
        displayName: Publish prod plan
        variables:
          - group: azuregovernanceprod
          - group: azuregovernanceprodsecret
        pool:
          vmImage: "ubuntu-latest"
        dependsOn: terraformInstall
        steps:
          - template: /pipelines/templates/tf-init-plan.yaml
            parameters:
              tfCliInit: -backend=true -backend-config=prod.stage
              tfCliPlan: -out prod.plan  -var-file=prod.tfvars.json

          - publish: src/terraform/prod.plan
            displayName: "Publish Prod Plan"
            artifact: releaseAzureGovernanceprodplan
            enabled: "true"

  - stage: dev

    variables:
      - group: azuregovernancedev
      - group: azuregovernancedevsecret

    jobs:
      - deployment: TerraformApplyPlan
        displayName: Terraform (Apply Plan)
        pool:
          vmImage: "ubuntu-latest"
        continueOnError: false
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /pipelines/templates/tf-init-applyplan.yaml
                  parameters:
                    tfCliInit: -backend=true -backend-config=$(Agent.BuildDirectory)/releaseAzureGovernance/dev.stage
                    tfCliApply: -var-file=$(Agent.BuildDirectory)/releaseAzureGovernance/dev.tfvars.json $(Agent.BuildDirectory)/releaseAzureGovernancedevplan/dev.plan
