name: azure.governance.publishrelease$(Rev:.r)

trigger:
  batch: "true"
  branches:
    include:
      - release/*
  paths:
    include:
      - src/terraform

pr: none

variables:
  - name: TF_INPUT
    value: "false"
  - name: TF_IN_AUTOMATION
    value: "true"
  - name: TF_VERSION
    value: 0.12.19

stages:
  - stage: publishRelease

    jobs:
      - job: publishArtifacts
        displayName: Publish Azure Governance Terraform files.

        pool:
          vmImage: "ubuntu-latest"

        steps:
          - publish: src/terraform
            displayName: "Release Azure Governance."
            artifact: releaseAzureGovernance
            enabled: "true"

  - stage: dev

    variables:
      - group: azuregovernancedev
      - group: azuregovernancedevsecret
      - name: TF_VAR_deploymentStage
        value: dev

    jobs:
      - job: Terraform
        displayName: Terraform Init-Plan
        pool:
          vmImage: "ubuntu-latest"

        container:
          image: rjfmachado.azurecr.io/terraform:${{ variables['TF_VERSION'] }}
          endpoint: rjfmachado.containers

        steps:
          - template: /pipelines/templates/tf-init-plan.yaml
            parameters:
              tfCliInit: -backend=true -backend-config=dev.stage
              tfCliPlan: -out dev.plan

          - publish: src/terraform/dev.plan
            displayName: "Publish Dev Plan"
            artifact: releaseAzureGovernance.devplan
            enabled: "true"

  - stage: prod

    variables:
      - group: azuregovernanceprod
      - group: azuregovernanceprodsecret
      - name: TF_VAR_deploymentStage
        value: prod

    jobs:
      - job: Terraform
        displayName: Terraform Init-Plan
        pool:
          vmImage: "ubuntu-latest"

        container:
          image: rjfmachado.azurecr.io/terraform:${{ variables['TF_VERSION'] }}
          endpoint: rjfmachado.containers

        steps:
          - template: /pipelines/templates/tf-init-plan.yaml
            parameters:
              tfCliInit: -backend=true -backend-config=prod.stage
              tfCliPlan: -out prod.plan

          - publish: src/terraform/prod.plan
            displayName: "Publish Prod Plan"
            artifact: releaseAzureGovernance.prodplan
            enabled: "true"
